import type { Metadata } from "next";
import Header from "@/includes/header/Header";
import Footer from "@/includes/Footer";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <main className="my-container text-secondary-color mt-[100px]">
        {children}
      </main>
      <Footer />
    </>
  );
}
